# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mensagens.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'mensagens.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmensagens.proto\"\x9a\x01\n\x0c\x44ispositivoR\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x10\n\x08\x65ndereco\x18\x05 \x03(\t\x12\x16\n\x0eheartbeat_port\x18\x06 \x01(\t\x12(\n\x0f\x66uncionalidades\x18\x07 \x03(\x0b\x32\x0f.Funcionalidade\">\n\x0e\x46uncionalidade\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x1e\n\nparametros\x18\x02 \x03(\x0b\x32\n.Parametro\"\'\n\tParametro\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\"\'\n\x0b\x44ispositivo\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"T\n\x08GatewayM\x12\x0f\n\x07\x63omando\x18\x01 \x01(\t\x12\x17\n\x0f\x65nderecoGateway\x18\x02 \x03(\t\x12\x1e\n\x16gateway_heartbeat_port\x18\x03 \x01(\t\"\xa5\x01\n\x08\x43lienteC\x12\x0f\n\x07\x63omando\x18\x01 \x01(\t\x12!\n\x0b\x64ispositivo\x18\x02 \x01(\x0b\x32\x0c.Dispositivo\x12\x16\n\x0e\x66uncionalidade\x18\x03 \x01(\t\x12\x1e\n\nparametros\x18\x04 \x03(\x0b\x32\n.Parametro\x12\x0f\n\x07novo_id\x18\x05 \x01(\t\x12\x1c\n\x14parametrosEscolhidos\x18\x06 \x03(\t\"/\n\tGatewayLD\x12\"\n\x0c\x64ispositivos\x18\x01 \x03(\x0b\x32\x0c.Dispositivo\"5\n\tGatewayLF\x12(\n\x0f\x66uncionalidades\x18\x01 \x03(\x0b\x32\x0f.Funcionalidade\"@\n\x11StatusDispositivo\x12\x14\n\x0cnomeDoStatus\x18\x01 \x01(\t\x12\x15\n\rvalorDoStatus\x18\x02 \x01(\t\"2\n\x0c\x44ispositivoS\x12\"\n\x06status\x18\x02 \x03(\x0b\x32\x12.StatusDispositivo\"S\n\tGatewayHB\x12\x0f\n\x07\x63omando\x18\x01 \x01(\t\x12\x1e\n\x16gateway_heartbeat_port\x18\x02 \x01(\t\x12\x15\n\rtamanho_lista\x18\x03 \x01(\t\"L\n\rDispositivoHB\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x16\n\x0eheartbeat_port\x18\x02 \x01(\t\x12\x15\n\rtamanho_lista\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mensagens_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISPOSITIVOR']._serialized_start=20
  _globals['_DISPOSITIVOR']._serialized_end=174
  _globals['_FUNCIONALIDADE']._serialized_start=176
  _globals['_FUNCIONALIDADE']._serialized_end=238
  _globals['_PARAMETRO']._serialized_start=240
  _globals['_PARAMETRO']._serialized_end=279
  _globals['_DISPOSITIVO']._serialized_start=281
  _globals['_DISPOSITIVO']._serialized_end=320
  _globals['_GATEWAYM']._serialized_start=322
  _globals['_GATEWAYM']._serialized_end=406
  _globals['_CLIENTEC']._serialized_start=409
  _globals['_CLIENTEC']._serialized_end=574
  _globals['_GATEWAYLD']._serialized_start=576
  _globals['_GATEWAYLD']._serialized_end=623
  _globals['_GATEWAYLF']._serialized_start=625
  _globals['_GATEWAYLF']._serialized_end=678
  _globals['_STATUSDISPOSITIVO']._serialized_start=680
  _globals['_STATUSDISPOSITIVO']._serialized_end=744
  _globals['_DISPOSITIVOS']._serialized_start=746
  _globals['_DISPOSITIVOS']._serialized_end=796
  _globals['_GATEWAYHB']._serialized_start=798
  _globals['_GATEWAYHB']._serialized_end=881
  _globals['_DISPOSITIVOHB']._serialized_start=883
  _globals['_DISPOSITIVOHB']._serialized_end=959
# @@protoc_insertion_point(module_scope)
